### ISSUE TITLE
Fonts & Logo

### ISSUE THREAD

**Issue by grayghostvisuals** [theronstudios/theronmoto#1]
@kennedysgarage Can you put the logo and the fonts on the master branch for me? Once I get those this will be completed for you as far as my work goes :+1:

**Comment by kennedysgarage** [comment]
• [SCSS for @font-face](https://github.com/theronstudios/theronstudios/blob/master/_assets/stylesheets/fontface.css.scss)
• [Porsche image](http://cl.ly/image/2I3j3J3e260B)
• [Logo](http://cl.ly/2J132S0y2h46)
• [Original Sketch file](http://cl.ly/162g1y0O1l44)

**Comment by grayghostvisuals** [comment]
@kennedysgarage Have you noticed something funky with the images during compiling? Only thing that is carried over from `_assets/images` into `_site/assets` is `cover2.jpg`. What the el is going down in chinatown brochacho?

**Comment by kennedysgarage** [comment]
@grayghostvisuals I have not noticed that, every seems to be working on my end. Maybe we can hop on Skype here in a few.
